// import { Metadata } from "next";
'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import './assets/nprogress.css';
import Router from "next/router";
// const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Providers>
             {children}
          </Providers>
      </body>
    </html>
  );
}
